# Generated by Django 6.0.3 on 2026-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10),
        ),
    ]
